export const ANALYZE_ATTACHMENT_MAX_BYTES = 10 * 1024 * 1024;
export const ANALYZE_ATTACHMENT_MAX_PAGES = 50;
export const ANALYZE_ATTACHMENT_MAX_TEXT_CODE_POINTS = 100_000;
export const ANALYZE_ATTACHMENT_MAX_OUTPUT_CODE_POINTS = 8_000;
export const ANALYZE_ATTACHMENT_DOWNLOAD_TIMEOUT_MS = 20_000;
export const ANALYZE_ATTACHMENT_PDF_TIMEOUT_MS = 20_000;
export const ANALYZE_ATTACHMENT_NIM_TIMEOUT_MS = 90_000;
export const ANALYZE_ATTACHMENT_JOB_TTL_MS = 10 * 60_000;
